# Generated by Django 5.1.2 on 2024-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
